"""add user profile and account fields

Revision ID: 0e03f0d17a01
Revises: c9a32832bee6
Create Date: 2026-07-25 10:46:38.325721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e03f0d17a01'
down_revision: Union[str, Sequence[str], None] = 'c9a32832bee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column(
    'users',
    sa.Column(
        'is_deleted',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###
